apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k53
  labels:
    {{- include "k53.labels" . | nindent 4 }}
rules:
- apiGroups:
  - src.bwag.me
  resources:
  - resolvers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - src.bwag.me
  resources:
  - resolvers/finalizers
  verbs:
  - update
- apiGroups:
  - src.bwag.me
  resources:
  - resolvers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - services
  - pods
  verbs:
  - get
  - list
  - watch