{{- if .Values.serviceMonitor.create -}}
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "k53.labels" . | nindent 4 }}
  name: k53-metrics-monitor
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
    - path: /metrics
      port: https
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      {{- include "k53.selectorLabels" . | nindent 6 }}
{{- end }}
