{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k53.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k53.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k53-role-binding
  labels:
    {{- include "k53.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k53
subjects:
- kind: ServiceAccount
  name: {{ include "k53.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
